import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { getSession, signIn, signOut, signUp, trustedDirectorySupabase } from './trustedDirectoryVault';
import { caretakerPairings, claimInvite } from '../pairing/patientCaretakerPairing';

const WARM = { ink: '#34271f', muted: '#705e51', paper: '#fffaf3', accent: '#9d4e32', line: '#e9dbca' };
const secretFrom = (value) => (value || '').trim().replace(/^cbc-pair-v1:/, '');

export default function CaretakerCloudSetup() {
  const [session, setSession] = useState(null);
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [label, setLabel] = useState(''); const [manualCode, setManualCode] = useState('');
  const [scannerOpen, setScannerOpen] = useState(false); const [permission, requestPermission] = useCameraPermissions();
  const [pairings, setPairings] = useState([]); const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('Sign in with the caretaker cloud account, then scan the patient’s one-time QR code.');
  const refresh = async () => { if (!session) return; try { setPairings(await caretakerPairings()); } catch (error) { setMessage(error?.message || 'Could not check caretaker pairings.'); } };

  useEffect(() => { if (trustedDirectorySupabase) getSession().then(setSession).catch(() => setMessage('Could not check caretaker cloud account status.')); }, []);
  useEffect(() => { refresh(); if (!session) return undefined; const interval = setInterval(refresh, 4000); return () => clearInterval(interval); }, [session]);
  if (!trustedDirectorySupabase) return <View style={styles.card}><Text style={styles.title}>Caretaker cloud pairing</Text><Text style={styles.copy}>Not configured yet. Add the Supabase URL and publishable key to the mobile environment, then rebuild. This never appears in Patient mode.</Text></View>;

  async function account(action) { setBusy(true); try { const next = action === 'signup' ? await signUp(email, password) : await signIn(email, password); if (!next) { setMessage('Check the caretaker email to confirm the account, then sign in.'); return; } setSession(next); setPassword(''); setMessage('Caretaker account connected. Enter the name the patient should see before scanning.'); } catch (error) { setMessage(error?.message || 'Caretaker account action failed.'); } finally { setBusy(false); } }
  async function beginScan() { if (!label.trim()) { setMessage('Enter the name or relationship the patient should see before scanning.'); return; } const result = permission?.granted ? permission : await requestPermission(); if (!result?.granted) { setMessage('Camera permission is needed only to scan the patient’s one-time pairing QR code.'); return; } setScannerOpen(true); }
  async function claim(value) { if (busy) return; const secret = secretFrom(value); if (!/^[0-9a-f]{64}$/i.test(secret)) { setMessage('That pairing code is not valid. Ask the patient to create a new one.'); return; } setBusy(true); setScannerOpen(false); try { await claimInvite(secret, label); setManualCode(''); setMessage('Request sent. The patient must approve it on their unlocked phone before this connection becomes active.'); await refresh(); } catch (error) { setMessage(error?.message || 'Could not claim this pairing code.'); } finally { setBusy(false); } }
  async function disconnect() { setBusy(true); try { await signOut(); setSession(null); setPairings([]); setScannerOpen(false); setMessage('Caretaker cloud account disconnected.'); } catch (error) { setMessage(error?.message || 'Could not disconnect the caretaker account.'); } finally { setBusy(false); } }

  if (!session) return <View style={styles.card}><Text style={styles.title}>Caretaker cloud pairing</Text><Text style={styles.copy}>Only a caretaker enters an email and password. The patient never needs these credentials.</Text><TextInput value={email} onChangeText={setEmail} placeholder="Caretaker email" keyboardType="email-address" autoCapitalize="none" style={styles.input} /><TextInput value={password} onChangeText={setPassword} placeholder="Caretaker cloud password" secureTextEntry style={styles.input} /><View style={styles.buttons}><Pressable style={styles.button} onPress={() => account('signin')} disabled={busy}><Text style={styles.buttonText}>Sign in</Text></Pressable><Pressable style={styles.secondary} onPress={() => account('signup')} disabled={busy}><Text style={styles.secondaryText}>Create account</Text></Pressable></View><Text style={styles.status}>{message}</Text></View>;
  return <View style={styles.card}><Text style={styles.title}>Connect to a patient phone</Text><Text style={styles.copy}>Connected as {session.user.email || 'caretaker'}. Scan a one-time QR shown by the unlocked patient phone; the patient must approve your request afterward.</Text><TextInput value={label} onChangeText={setLabel} placeholder="Your name or relationship (for example, Asha — daughter)" maxLength={80} style={styles.input} />{scannerOpen ? <View style={styles.scanner}><CameraView style={styles.camera} facing="back" onBarcodeScanned={({ data }) => claim(data)} barcodeScannerSettings={{ barcodeTypes: ['qr'] }} /><Pressable style={styles.secondary} onPress={() => setScannerOpen(false)} disabled={busy}><Text style={styles.secondaryText}>Cancel scan</Text></Pressable></View> : <Pressable style={styles.button} onPress={beginScan} disabled={busy}><Text style={styles.buttonText}>Scan patient QR code</Text></Pressable>}<TextInput value={manualCode} onChangeText={setManualCode} placeholder="Or paste/type the pairing code" autoCapitalize="none" style={styles.input} /><Pressable style={styles.secondary} onPress={() => claim(manualCode)} disabled={busy}><Text style={styles.secondaryText}>Send pairing request</Text></Pressable>{pairings.length ? <View style={styles.pairings}><Text style={styles.requestTitle}>Active patient connections</Text>{pairings.map((pairing) => <Text key={pairing.id} style={styles.status}>• Approved {new Date(pairing.created_at).toLocaleDateString()} — encrypted sharing is not enabled yet.</Text>)}</View> : null}<Text style={styles.status}>{message}</Text><Pressable style={styles.secondary} onPress={disconnect} disabled={busy}><Text style={styles.secondaryText}>Disconnect caretaker account</Text></Pressable></View>;
}

const styles = StyleSheet.create({ card: { backgroundColor: WARM.paper, borderWidth: 1, borderColor: WARM.line, borderRadius: 18, padding: 18, gap: 10 }, title: { color: WARM.ink, fontSize: 18, fontWeight: '800' }, copy: { color: WARM.muted, lineHeight: 20 }, input: { minHeight: 46, borderWidth: 1, borderColor: '#d9c4ae', borderRadius: 10, backgroundColor: '#fffdfa', padding: 11, color: WARM.ink }, buttons: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, scanner: { gap: 10 }, camera: { width: '100%', height: 280, borderRadius: 12, overflow: 'hidden', backgroundColor: '#201813' }, pairings: { borderTopWidth: 1, borderTopColor: WARM.line, paddingTop: 10, gap: 5 }, requestTitle: { color: WARM.ink, fontWeight: '800' }, button: { alignSelf: 'flex-start', borderRadius: 9, backgroundColor: WARM.accent, paddingHorizontal: 14, paddingVertical: 11 }, buttonText: { color: WARM.paper, fontWeight: '800' }, secondary: { alignSelf: 'flex-start', borderWidth: 1, borderColor: '#cba98f', borderRadius: 9, paddingHorizontal: 14, paddingVertical: 10 }, secondaryText: { color: '#75432f', fontWeight: '800' }, status: { color: WARM.muted, lineHeight: 19, fontSize: 13 } });
